# Generated by Django 5.0.2 on 2024-02-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaptopApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.TextField(max_length=500),
        ),
    ]
