# Generated by Django 5.0.2 on 2024-02-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaptopApp', '0002_alter_product_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display',
            field=models.TextField(default='11/12/12', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='gc',
            field=models.TextField(default='ghsjsn', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='os',
            field=models.TextField(default='sisk', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='processor',
            field=models.TextField(default='syshhii', max_length=100),
            preserve_default=False,
        ),
    ]
