# Generated by Django 5.0.2 on 2024-02-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaptopApp', '0003_product_display_product_gc_product_os_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='memory',
            field=models.TextField(default='12hbhb', max_length=100),
            preserve_default=False,
        ),
    ]
